services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: talkdb
    ports:
      - "5432"
    volumes:
      - ./talk-api/talks.sql:/docker-entrypoint-initdb.d/talks.sql:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  talk-api:
    image: talk-api:latest
    build: ./talk-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/talkdb?sslmode=disable
      PORT: "8080"
    ports:
      - "8080"

  speaker-api:
    image: speaker-api:latest
    build: ./speaker-api
    ports:
      - "5000"

  frontend:
    depends_on:
    - speaker-api
    - talk-api
    image: frontend:latest
    build: ./frontend
    environment:
      NEXT_TALK_API_HOST: http://talk-api:8080
      NEXT_SPEAKER_API_HOST: http://speaker-api:5000
    ports:
      - "3000:3000"

########################################################
# Ignore everything below, you won't have to touch it. #
########################################################

  otel-collector:
    depends_on:
      - prometheus
      - tempo
    image: otel/opentelemetry-collector-contrib:0.139.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./configs/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317"   # OTLP gRPC receiver
      - "4318"   # OTLP protobuf receiver

  prometheus:
    image: quay.io/prometheus/prometheus:v3.7.3
    command:
      - --storage.tsdb.retention.time=7d
      - --config.file=/etc/config/prometheus.yml
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-otlp-receiver
      - --web.enable-remote-write-receiver
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/config/prometheus.yml
      - prometheus-data:/prometheus

  grafana:
    depends_on:
      - prometheus
      - tempo
    image: grafana/grafana:12.4.0-19358656895
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    ports:
      - "3001:3000"
    volumes:
      - ./configs/grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana

  tempo:
    image: grafana/tempo:2.9.0
    command: ["-config.file=/etc/tempo.yaml" ]
    user: root
    ports:
      - "3200"
      - "4317"
      - "9097"
    volumes:
      - ./configs/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/lib/tempo

volumes:
  grafana-data: {}
  prometheus-data: {}
  tempo-data: {}
