discovery:
  instrument:
    - open_ports: 3000
      exe_path: /usr/local/bin/node
    - open_ports: 5000
    - open_ports: 8080
otel_metrics_export:
  endpoint: http://otel-collector:4318
otel_traces_export:
  endpoint: http://otel-collector:4318
